// get Apis
export const ALL_API_REQUEST ="ALL_API_REQUEST"
export const ALL_API_SUCCESS = "ALL_API_SUCCESS";
export const ALL_API_FAIL = "ALL_API_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


// admin API request
export const ADMIN_API_REQUEST = "ADMIN_API_REQUEST";
export const ADMIN_API_SUCCESS = "ADMIN_API_SUCCESS";
export const ADMIN_API_FAIL = "ADMIN_API_FAIL";

// create new API --> admin

export const NEW_API_REQUEST = "NEW_API_REQUEST";
export const NEW_API_SUCCESS = "NEW_API_SUCCESS";
export const NEW_API_RESET = "NEW_API_RESET";
export const NEW_API_FAIL = "NEW_API_FAIL";

// API details --> 
export const API_DETAILS_REQUEST = "API_DETAILS_REQUEST";
export const API_DETAILS_SUCCESS = "API_DETAILS_SUCCESS";
export const API_DETAILS_RESET = "API_DETAILS_RESET";
export const API_DETAILS_FAIL = "API_DETAILS_FAIL";


// Add a review
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";



// Delete API
export const DELETE_API_REQUEST = "DELETE_API_REQUEST";
export const DELETE_API_SUCCESS = "DELETE_API_SUCCESS";
export const DELETE_API_RESET = "DELETE_API_RESET";
export const DELETE_API_FAIL = "DELETE_API_FAIL";

//Udate API =>
export const UPDATE_API_REQUEST = "UPDATE_API_REQUEST";
export const UPDATE_API_SUCCESS = "UPDATE_API_SUCCESS";
export const UPDATE_API_RESET = "UPDATE_API_RESET";
export const UPDATE_API_FAIL = "UPDATE_API_FAIL";


// get all review --> admin

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";



// delete review admin =>
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
